### ISSUE TITLE
Just making sure... no sound from DOS (GOG version)

### ISSUE THREAD

**Issue by ibara** [OpenFodder/openfodder#14]
Just making sure I'm not crazy. Reading over the code, it seems like there's no mechanism for finding and playing the music from the DOS version of the game (I'm using the GOG version).

It's OK if no. The OpenBSD package can just tell the user to go find their own music assets and put them in the right place. I'm double checking to make sure I didn't miss anything.

**Comment by segrax** [comment]
Hey Brian,

Appologies for the delay, 

You are correct, there is no routines to decode/play the music included with the DOS release(s).
Although i'll be happy to merge said routines, if someone wants to develop them :)

The reason they're missing is 2 part, partly because the music code (SoundBlaster Playback) was larger than the actual game code itself (maybe another opensource project could be valuable here?)

secondly, as a kid i played the Amiga Cannon Fodder release, and the Dos music is a real put off -- IMO it would be awesome if we could convince GOG to package OpenFodder with the Dos graphics, and the Amiga sound files (instead of the current DosBox release), as its been impossible to purchase that release for over 20 years now (outside of eBay) :(

**Comment by ibara** [comment]
No worries. In other news, there is now an OpenBSD package of OpenFodder: http://openports.se/games/openfodder

**Comment by segrax** [comment]
Thats great news,

Thanks for your work on this!!
