### ISSUE TITLE
Which are the command line argument for OpenFodder?

### ISSUE THREAD

**Issue by xcom169** [OpenFodder/openfodder#24]
Which are the possible command line arguments for OpenFodder? OpenFodder --help gives me a 'Core Dump'.
In which .cpp these arguments are handled?

Thanks!

**Comment by segrax** [comment]
The CLI support is pretty much non-existant, and the ones which are implemented, are done very poorly (hence why its crashing, its trying to access argument 2, which clearly wont exist if you just OpenFodder --help)

Just Here:
https://github.com/OpenFodder/openfodder/blob/master/Source/stdafx.cpp#L40

commands are:

skipintro
map

but, due to extreme lazyness, they must be used in exactly the right spots in the argument list.

Improvement is on our TODO :)

**Comment by segrax** [comment]
Done,

Have added a number of CLI options, you can view with --help

  -h, --help             Help
  -w, --window           Start in window mode
      --skipintro        Skip all game intros
  -c, --campaign "name"  Campaign Name (default: )
  -m, --mission 1        Mission Number (default: 0)
  -p, --phase 2          Phase Number (default: 0)
      --list-campaigns   List available campaigns
