### ISSUE TITLE
Cannon Fodder 2 detection

### ISSUE THREAD

**Issue by VonKossa** [OpenFodder/openfodder#32]
Hi!

I am unable to get CF2 to get detected, i have tried to put all data in the Dos2_CD directory and only CF_ENG.DAT. No difference.
Is there different versions of CF2?

**Comment by segrax** [comment]
Hey,

I believe all PC versions are the same, but even if not, it should still work and just give a warning about MD5 hash not matching.

Are the demos working?

**Comment by segrax** [comment]
also, have you downloaded the data pack? (it contains the campaign info and the demos)

**Comment by VonKossa** [comment]
Yes i have downloaded the 1.5.1 datapack, didn´t find a newer one.
Cannon Fodder, PC and Cannon Fodder Amiga works and the demos work.
There is a CF2 folder under DATA.

________________________________

**Comment by segrax** [comment]
are you getting any console output on startup?

**Comment by VonKossa** [comment]
I´m not sure, i have to check that this evening.

________________________________

**Comment by VonKossa** [comment]
No, nothing at all on the console output.

**Comment by segrax** [comment]
ugh, thats problematic...

if the data was bad, it should report an MD5 warning on startup
which makes me think it cant find it at all, but the Dos2_CD folder is the right place for it

what happens if you put the CF_ENG.DAT from the CF2, into the Dos_CD folder?

Are you using any of the paths defined in the install.md for the data, or putting it in the working directory with the executable?


![image](https://user-images.githubusercontent.com/1327406/52385059-28f3a400-2ad4-11e9-8806-8d3059c1847f.png)

**Comment by daninthemix** [comment]
I have this issue too. When the installer asked me to select CF1 and 2 locations, I pointed it to the GOG install locations of both. But there is no Cannon Fodder 2 in the menu (nor is there Cannon Fodder 1 - but by selecting 'PC Version' it appears to launch CF1).

**Comment by VonKossa** [comment]
>what happens if you put the CF_ENG.DAT from the CF2, into the Dos_CD folder?

I don´t know, i´ll test and report back.

>Are you using any of the paths defined in the install.md for the data, or putting it in the working directory with the executable?

In the working directory in the /Data/Dos2_CD folder.


The detection of the CF_ENG.DAT, is it case sensitive?
I have tested with all upper case and all lower case, in the CF1 scenario it is all uppercase and it is working for CF1.
Can it be a strange combination in the CF2 scenario of upper and lower case characters which makes it undetectable under Linux, for example CF_eng.Dat?

**Comment by VonKossa** [comment]
If i start Openfodder with CF2 CF_ENG.DAT into the Dos_CD folder i get the following error:
Cannon Fodder: CF_ENG.DAT Unknown MD5: 8A3EB9B9F134B2997E6534D4C39B23D6

**Comment by segrax** [comment]
> 
> 
> I have this issue too. When the installer asked me to select CF1 and 2 locations, I pointed it to the GOG install locations of both. But there is no Cannon Fodder 2 in the menu (nor is there Cannon Fodder 1 - but by selecting 'PC Version' it appears to launch CF1).

The 'PC Version' will be the PC format demo, are you able to browse to '%USERPROFILE%/Documents/OpenFodder/Data/Dos_CD' and see what files are in there?

**Comment by daninthemix** [comment]
It's just an empty file called '_DosCDDataHere'

**Comment by segrax** [comment]
> 
> what happens if you put the CF_ENG.DAT from the CF2, into the Dos_CD folder?
> I don´t know, i´ll test and report back.
> Are you using any of the paths defined in the install.md for the data, or putting it in the working directory with the executable?
> In the working directory in the /Data/Dos2_CD folder. The detection of the CF_ENG.DAT, is it case sensitive? I have tested with all upper case and all lower case, in the CF1 scenario it is all uppercase and it is working for CF1. Can it be a strange combination in the CF2 scenario of upper and lower case characters which makes it undetectable under Linux, for example CF_eng.Dat?

Detection being case sensitive is dependent on the OS, but it will check for both CF_ENG.DAT and cf_eng.dat if it doesnt find CF_ENG.DAT (which is the original filename -- unfortunately there is a mix in some versions of all UPPER and all LOWER)

On a bright note, that MD5 error was expected, however its still puzzling as to why it cant find it in the Dos2_CD folder

I'm going to start looking into a way to replace this part of the engine, too many people are having problems

**Comment by segrax** [comment]
> 
> 
> It's just an empty file called '_DosCDDataHere'

Something must of gone wrong with the copy from the GOG release, are you able to copy CF_ENG.DAT from your GOG CF1 release into that folder?

**Comment by VonKossa** [comment]
>I'm going to start looking into a way to replace this part of the engine, too many people are >having problems

Great, thanks for your help

**Comment by daninthemix** [comment]
Copying CF_ENG.DAT into that folder has made Cannon Fodder show up. However, the same doesn't work for Cannon Fodder 2 if I copy it into the Dos2_CD folder. Don't know if it matters, but Cannon Fodder 2's CF_ENG.DAT is only 712kb - smaller than CF1's (these are both from GOG).

(p.s. if it's not too much trouble and you're making changes anyway, can you include those cheats in the release build?)

**Comment by segrax** [comment]
> 
> 
> Copying CF_ENG.DAT into that folder has made Cannon Fodder show up. However, the same doesn't work for Cannon Fodder 2 if I copy it into the Dos2_CD folder. Don't know if it matters, but Cannon Fodder 2's CF_ENG.DAT is only 712kb - smaller than CF1's (these are both from GOG).
> 
> (p.s. if it's not too much trouble and you're making changes anyway, can you include those cheats in the release build?)

712Kb is normal (see the screenshot above)

I'm kind of stumped as to what the problem is here, can you just verify inside your Campaigns folder that "Cannon Fodder 2.ofc" exists?

Yeah, i can enable those for retail build, would a CLI option (eg. --cheats) be alright? I'm reluctant to permanently enable them, as it becomes too easy to just cheat :)

**Comment by daninthemix** [comment]
Yes, full path is:

"C:\Users\Dan\Documents\OpenFodder\Campaigns\Cannon Fodder 2.ofc"

File is 19kb.

Yes a CLI option for cheats would be perfect.

EDIT: don't know if it matters but the special 'My Documents' Windows folder is redirected, so the OpenFodder folder above is literally the only folder in "C:\Users\Dan\Documents\OpenFodder\".

**Comment by daninthemix** [comment]
OK sorry I was being an idiot - just CF_ENG.DAT was enough to make Cannon Fodder appear, but not CF2. For that I've copied the entire GOG folder into Dos2_CD and now it's showing up.

**Comment by VonKossa** [comment]
Iḿ happy for you, if i copy the whole folder of CF2 under linux it doesn´t show up. :(

**Comment by VonKossa** [comment]
Inspired by above results i copied the whole CF2 folder and changed every file to uppercase, and lo and behold. It appeared in the menu! Woho!
But there is no music! :(

**Comment by segrax** [comment]
> 
> 
> Inspired by above results i copied the whole CF2 folder and changed every file to uppercase, and lo and behold. It appeared in the menu! Woho!
> But there is no music! :(

That's certainly semi good news 
Apologies for the extremely bad experience you've had so far :)

The music may depend on which version of SDL2/SDL2_mixer is installed, there was at-least one bug introduced into SDL2_Mixer over the last year (which was still present last time i tested on Ubuntu), which prevented certain music files playing (mostly it seemed to break VOC, but we didn't support CF2 at the time)

**Comment by segrax** [comment]
> 
> 
> OK sorry I was being an idiot - just CF_ENG.DAT was enough to make Cannon Fodder appear, but not CF2. For that I've copied the entire GOG folder into Dos2_CD and now it's showing up.

Interesting, thanks for the feedback, what is strange... I tested it this morning with only CF_ENG.DAT in the CF2 folder, and it came up :/

**Comment by VonKossa** [comment]
> > Inspired by above results i copied the whole CF2 folder and changed every file to uppercase, and lo and behold. It appeared in the menu! Woho!
> > But there is no music! :(
> 
> That's certainly semi good news
> Apologies for the extremely bad experience you've had so far :)
> 
> The music may depend on which version of SDL2/SDL2_mixer is installed, there was at-least one bug introduced into SDL2_Mixer over the last year (which was still present last time i tested on Ubuntu), which prevented certain music files playing (mostly it seemed to break VOC, but we didn't support CF2 at the time)

I found the reason, sdl2-mixer had to be compiled with mod and modplug support.
Funny thing is that CF1 does not need mod support.

**Comment by segrax** [comment]
> I found the reason, sdl2-mixer had to be compiled with mod and modplug support.
> Funny thing is that CF1 does not need mod support.

The Dos CF releases have different audio system to all the other versions, while CF1/2 on Amiga use the exact same setup

Dos CF1 uses a combination of VOC and Adlib/Roland (although we never implemented these two)
Dos CF2 uses AMF (Advanced music format) for music and raw 8bit samples for sound effects

Amiga CF1/CF2 both use RJP for audio


VOC can be decoded by standalone SDL2_mixer, but AMF requires modplug

The decoder for RJP is built into OF (Thanks to ScummVM), and only requires the standard SDL2_Mixer


if it helps at all, over the weekend we made a change so that 

**you can now drop the Amiga music files into the Dos_CD / Dos2_CD folder and the engine will use those instead**

**Comment by segrax** [comment]
an overhaul of resource management has been done, it should hopefully resolve some of these upper/lower case issues

**Comment by andrew-mcmahon** [comment]
I thought it might be helpful to post the md5 hashes and filenames for the bare minimum of files to run each game. As the install doc mentions the [data pack](https://github.com/OpenFodder/data/releases/download/1.6.0/Data.pack.1.6.0.zip) is mandatory. (as a bonus it contains the better sounding Amiga audio files so no need to look for those!)  
Perhaps the readme and install docs could be updated.
  
**Cannon Fodder DOS**  
`eeb82d5a6b14e7e59c8f7b5169bfcd55 CF_ENG.DAT`

**Cannon Fodder 2 DOS**
```
efe57bf26bba0c7ac35720eb86ae37ea  BIRD.SMP
8a3eb9b9f134b2997e6534d4c39b23d6  CF_ENG.DAT
124efa03f13669d59eb03f1812a71624  DIE1.SMP
902e437b8257231d1494535170a9ed22  DIE2.SMP
4426ae305e6908fd6a933a3522681cec  DIE3.SMP
331f9da882304ec428dd84051b7ea003  DUCK.SMP
ab3eb80b15df9ad87fc6ab23e5c8adaf  ENGINE.SMP
18151d71549006032f3099ec1457699c  EXPLOSN.SMP
0aa5d2c3849d9522c54f24b4900755ca  GAMEOVER.AMF
3ca15373e824cef8622216b2b6835c26  GRENADE.SMP
1312b6a5d43bf1d3137cd29d5ce5403a  GUN.SMP
c70228bf18b4789796132e2b7b5676c7  HELIANIM.AMF
26e2fae3c85e728edfc94b5cf9ea98c0  HELI.SMP
23bba2b5c1863488071515ed0e7b13b1  LOADER.AMF
9c58f6a8e4c79388994c34b6155e2fba  MENU.AMF
16688e86d89d80f9b5f956be9fc63c65  MGUN.SMP
c7625e6e1a6fea368a104646390ab243  MISSILE.SMP
16233c3d4d205d32720a3f65a224190f  ROOK.SMP
99d397e27fcacd3ef7d0abc42233a558  SHEEP.SMP
7831a09310004bb0f2f6754ba52d0ad5  TITLE.AMF
1e61f47ce71d24828f2a1e1656786978  WINLEVEL.AMF
b9333dbb4bd65aef6e3ba801d4fdabed  WINZONE.AMF
```  
I couldn't see any terminal output listing missing files when I ran the game so I was wondering why _Cannon Fodder 2_ wasn't showing up (I only copied CF_ENG.DAT to Dos2_CD)
I probably haven't played Cannon Fodder for about 20 years since the Amiga 500+ so it's nice to have a go of it again.  
No issues with compiling the latest master branch under Debian Testing; the only thing which caught me out was needing clang++ instead of g++.
Would/could the game benefit in any way from a resolution boost or perhaps a graphics filter (like hq3x) or would that be an absolute nightmare to add?
Oh and thanks for making this! =D

EDIT: I should've poked around a bit more in the source files - I can see a [list of game files here](https://github.com/OpenFodder/openfodder/blob/master/Source/Versions_Files.hpp)

**Comment by segrax** [comment]
> I couldn't see any terminal output listing missing files when I ran the game so I was wondering why _Cannon Fodder 2_ wasn't showing up (I only copied CF_ENG.DAT to Dos2_CD)

That is probably something that could be fixed now actually, will open a new issue for it (https://github.com/OpenFodder/openfodder/issues/46)

Thanks for reporting!
