### ISSUE TITLE
How to play normal 1 player game? (Original Amiga CF1 campaign)

### ISSUE THREAD

**Issue by vanfanel** [OpenFodder/openfodder#43]
Hi there!

I have just built latest GIT version of OpenFodder, but I dont seem to be able to play the original Amiga campaign (intro, then hill, then first level, etc...)
All I can see upon running the executable is a menu where I can select a level!
My original AMIGA data lives in ~/openfodder/Data/Amiga, as per instructions.

Thanks!

**Comment by drnovice** [comment]
Hi!
What OS are you using?

**Comment by segrax** [comment]
Hi @vanfanel ,

Which options can you see on the menu? if "Cannon Fodder" is visible, select it and the intro will start :)

**Comment by vanfanel** [comment]
@drnovice I use GNU/Linux. Lubuntu 18.04 x86_64 to be precise.
@segrax I can only see "Single map" and "Random Map", while the mission intro music plays.

**Comment by segrax** [comment]
It sounds like its finding the game data then, otherwise you wouldn't even reach the menu :)

Have you downloaded/extracted the data pack? typically if the campaigns are missing from the menu, its because their information isn't available

https://github.com/OpenFodder/data/releases/download/1.6.0/Data.pack.1.6.0.zip


https://github.com/OpenFodder/openfodder/blob/master/INSTALL.md

**Comment by vanfanel** [comment]
@segrax Thanks! That was it! I was missing the Data Pack files... Now I can start a normal Amiga campaign!! Great!!
