### ISSUE TITLE
How to create Track2.flv

### ISSUE THREAD

**Issue by monreal** [OpenFodder/openfodder#8]
The readme says "Extract Track2 from the CD and name it 'Track2.flv', placed in the Amiga_CD folder."

I wonder how to actually do this. What kind of file format is "flv" and how to create it? Could you please also provide a checksum of the resulting file?

**Comment by segrax** [comment]
Hi,

It depends which operating system you're using, but its just an image of the second track on the CD32 Disk.

Unfortunately it also won't actually help, because I just realised, the code to play the cd32 movie after winning the game hasn't actually been implemented yet.

SHA256 of Track2 is 974413EA23B3A3619FB8A1265EEEFE66336BFB9AD17089223E93532DF405AD88

**Comment by monreal** [comment]
Thanks for the information.
